<?php
namespace Home\Controller;
use Think\Controller;
class SandnController extends Controller{
    /**
    *默认页控制
    */
    public function index(){
        /*获取攻略*/
        $model1=M('strategy');
        $strategy=$model1->limit(4)->select();
        /*获取游记*/
        $model2=M('note');
        $note=$model2->where("status=1")->limit(4)->select();
        /*根据赞的数量获取置顶攻略*/
        $topstrategy=$model1->select();
        $snum=count($topstrategy);
        for($i=0;$i<$snum;$i++){
            $maxpraise=$topstrategy[0]['praise'];
            if($maxpraise<=$topstrategy[$i]['praise']){
                $top=$topstrategy[$i];
            }
        }
        //var_dump(count($topstrategy));
        /*获取热门游记*/
        $where['status']=1;
        $where['ishot']=1;
        $hotnote=$model2->where($where)->limit(4)->select();
        /*获取热门攻略*/
        $hotstrategy=$model1->where('ishot=1')->limit(4)->select();
        $links=getLinks();
        $this->assign('links',$links);
        $this->assign(array(
            'strategy'=>$strategy,
            'note'=>$note,
            'top'=>$top,
            'hotnote'=>$hotnote,
            'hotstrategy'=>$hotstrategy,
        ));
        //var_dump($strategy);
        $this->display();
    }
    /**
    *更多页控制页
    */
    public function more(){
        /*攻略显示*/
        $strategy=M('strategy');
        $count=$strategy->count();// 查询满足要求的总记录数
        $Page=new \Think\Page($count,5);// 实例化分页类 传入总记录数和每页显示的记录数(2)
        $Page->setConfig('prev','上一页');
        $Page->setConfig('next','下一页');
        $show=$Page->show();// 分页显示输出
        // 进行分页数据查询 注意limit方法的参数要使用Page类的属性
        $list = $strategy->order('time')->limit($Page->firstRow.','.$Page->listRows)->select();
        $this->assign('list',$list);// 赋值数据集
        $this->assign('page',$show);// 赋值分页输出
        /*游记显示*/
        $list1=M('note as a')->join('user as b on b.id=a.user_id')->where('a.status=1')->field('a.id as id,a.title as title,b.username as username,a.time as time,a.areas as areas,a.praise as praise,a.pic as pic')->order('time')->select();
        //var_dump($list1);
        //获取热门景点
        $hotspot=M('spot')->where('type=3')->limit(4)->select();
        $links=getLinks();
        $this->assign('links',$links);
        $this->assign('list1',$list1);
        $this->assign('hotspot',$hotspot);
        $this->display(); // 输出模板
    }
    /**
    *官方攻略页控制
    */
    public function strategyview($id){
        $id=intval($id);
        $data=M('strategy')->find($id);
        //var_dump($data['cate_id']);
        /*获取相关地区*/
        $areas=explode(',',$data['areas']);
        /*获取相关景点*/
        $spots=explode(',',$data['spots']);
        $count=count($spots);
        $spot=M('spot');
        $spotsname=array();
        $spotsaddress=array();
        for($i=0;$i<$count;$i++){
            $id=intval($spots[$i]);
            $spotsname[]=$spot->where('id=%d',$id)->getField('name');
            $spotsaddress[]=$spot->where('id=%d',$id)->getField('address');
        }
        /*获取收藏信息*/
        $where['collection_id']=$data['id'];
        $where['user_id']=intval(session('userinfo.id'));
        $where['cate_id']=$data['cate_id'];
        $result=M('collection')->where($where)->find();
        if($result){
            $ifcollection=1;
        }else{
            $ifcollection=0;
        }
        /*获取收藏数量*/
        $collectionnumwhere['collection_id']=$data['id'];
        $collectionnumwhere['cate_id']=$data['cate_id'];
        $collection_number=M('collection')->where($collectionnumwhere)->count();
        //var_dump($data['id']);
        //var_dump($result);
        $spotsaddress=implode(',',$spotsaddress);
        $links=getLinks();
        $this->assign('links',$links);
        $this->assign(array(
            'data'=>$data,
            'areas'=>$areas,
            'spotsname'=>$spotsname,
            'spotsaddress'=>$spotsaddress,
            'ifcollection'=>$ifcollection,
            'collection_number'=>$collection_number,
        ));
        $this->display();
    }
    /**
    *攻略点赞
    */
    public function strategy_praise($id){
        $where['id']=intval($id);
        if(cookie('visitinfo')!=$id){
            //$data['praise']+=1;
            $result=M('strategy')->where($where)->setInc('praise');
            if($result){
                $praise=M('strategy')->where($where)->getField('praise');
                cookie('visitinfo',$id,3600);
                $data['praise']=$praise;
                $data['key']=1;
                $this->ajaxReturn($data);
            }else{
                $praise=M('strategy')->where($where)->getField('praise');
                $data['praise']=$praise;
                $data['key']=0;
                $this->ajaxReturn($data);
            }
        }else{
            $praise=M('strategy')->where($where)->getField('praise');
            $data['praise']=$praise;
            $data['key']=0;
            $this->ajaxReturn($data);
        }
    }
    /**
    *游记详情页
    */
     public function noteview($id){
        $id=intval($id);
        $data=M('note')->find($id);
        /*获取作者信息*/
        $person=M('user')->where('id=%d',$data['user_id'])->find();
        //var_dump($person);
        /*获取相关地区*/
        $areas=explode(',',$data['areas']);
        /*获取相关景点*/
        $spots=explode(',',$data['spots']);
        $count=count($spots);
        $spot=M('spot');
        $spotsname=array();
        $spotsaddress=array();
        for($i=0;$i<$count;$i++){
            $id=intval($spots[$i]);
            $spotsname[]=$spot->where('id=%d',$id)->getField('name');
            $spotsaddress[]=$spot->where('id=%d',$id)->getField('address');
        }
        /*获取收藏信息*/
        $where['collection_id']=$data['id'];
        $where['user_id']=intval(session('userinfo.id'));
        $where['cate_id']=$data['cate_id'];
        $result=M('collection')->where($where)->find();
        if($result){
            $ifcollection=1;
        }else{
            $ifcollection=0;
        }
        /*获取收藏数量*/
        $collectionnumwhere['collection_id']=$data['id'];
        $collectionnumwhere['cate_id']=$data['cate_id'];
        $collection_number=M('collection')->where($collectionnumwhere)->count();
        /*获取评论*/
        $comment=getComment(0,$data['id']);
        //var_dump($data['id']);
        //var_dump($result);
        $spotsaddress=implode(',',$spotsaddress);
        $links=getLinks();
        $this->assign('links',$links);
        $this->assign(array(
            'data'=>$data,
            'areas'=>$areas,
            'spotsname'=>$spotsname,
            'spotsaddress'=>$spotsaddress,
            'ifcollection'=>$ifcollection,
            'collection_number'=>$collection_number,
            'person'=>$person,
            'comment'=>$comment,
        ));
        $this->display();
    }
    /**
    *游记点赞
    */
    public function note_praise($id){
        $where['id']=intval($id);
        if(cookie('visitinfo')!=$id){
            //$data['praise']+=1;
            $result=M('note')->where($where)->setInc('praise');
            if($result){
                $praise=M('note')->where($where)->getField('praise');
                cookie('visitinfo',$id,3600);
                $data['praise']=$praise;
                $data['key']=1;
                $this->ajaxReturn($data);
            }else{
                $praise=M('note')->where($where)->getField('praise');
                $data['praise']=$praise;
                $data['key']=0;
                $this->ajaxReturn($data);
            }
        }else{
            $praise=M('note')->where($where)->getField('praise');
            $data['praise']=$praise;
            $data['key']=0;
            $this->ajaxReturn($data);
        }
    }
}
?>